spring:
  application:
    name: demo

  # gateway?? ?? ??? ????? ??? ???
  cloud:
    gateway:
      routes:
        # ???? ???? ?? ??? id?? ?? ???.
        # ?? ???? ??? ? ?? ??? id? ??? ?????.
        - id: simple-service
          # uri? ??? ?? ??? ?? ??? ??? ?????.
          # ? ?? simple-service ??? ? ?? spring ????? ?? ?? ?
          # ? spring ????? ?? ??? 12345 ? ??? ??? ????.
          uri: http://localhost:12345
          # predicates? ??? ??? ?????.
          # ?? ??? ??? ?? ? ??? ???? ??????.
          # /api/simple/create, /api/simple/read, /api/simple/update ?? ???
          # /api/simple/ ??? ?? simple-service? ??? ????.
          predicates:
            - Path=/api/simple/**
          filters:
            - StripPrefix=2

  # Spring Gateway ???? ??? 7890?? ????.
  server:
    port: 7890

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
