spring:
  application:
    name: demo

  # gateway?? ?? ??? ????? ??? ???
  cloud:
    gateway:
      routes:
        # ???? ???? ?? ??? id?? ?? ???.
        # ?? ???? ??? ? ?? ??? id? ??? ?????.
        # ?? ?? ? `-` ? ????? ????? ???.
        - id: simple-service
          # uri? ??? ?? ??? ?? ??? ??? ?????.
          # ? ?? simple-service ??? ? ?? spring ????? ?? ?? ?
          # ? spring ????? ?? ??? 12345 ? ??? ??? ????.
#          uri: http://localhost:12345
          uri: lb://SIMPLE
          # predicates? ??? ??? ?????.
          # ?? ??? ??? ?? ? ??? ???? ??????.
          # /api/simple/create, /api/simple/read, /api/simple/update ?? ???
          # /api/simple/ ??? ?? simple-service? ??? ????.
          predicates:
            - Path=/api/simple/**
          filters:
            - StripPrefix=2

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

# Spring Gateway ???? ??? 7890?? ????.
server:
  port: 7890

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9876/eureka