version: "3"

services:
  html-container:
    build:
      context: ./html-container
    ports:
      - "80:80"
    networks:
      - app-network

  html-css-test:
    build:
      context: ./html-css-test-app
    ports:
      - "3001:3001"
    networks:
      - app-network
  javascript-test-app:
    build:
      context: ./javascript-test-app
    ports:
      - "3002:3002"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge