spring:
  application:
    name: book

server:
  port: 12346

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9876/eureka

logging:
  level:
    com.example.simple.client: DEBUG
    feign: DEBUG